### ISSUE TITLE
039_video OSX Build will not play video

### ISSUE THREAD

**Issue by EricEisaman** [lewislepton/kha-tutorial-series#1]
After implementing the technique shown in your 039_video tutorial, my OSX build would not play the video however, my <a href="https://ericeisaman.github.io/mod7.html" target="_blank">HTML5 build</a> would.
<img src="https://d85.imgup.net/issuea8b5.gif" width="800px">

**Comment by lewislepton** [comment]
currently osx video is not 100%
it is fine in ios. been meaning to maybe use the source from ios & put into osx

**Comment by EricEisaman** [comment]
Noted. Thanks. 👍

**Comment by lewislepton** [comment]
yo @EricEisaman - just to let you know this morning a commit went out & macOS support for video is working. audio is not right now, but will come hopefully sooner than later ;)

so if you are using the git version of kha, then it will be ready to abuse ;)

**Comment by EricEisaman** [comment]
@lewislepton  Thanks Lewis.  I teach high school computer science, maths, and pre-engineering.  Some of my students and I have been assessing the benefits of working with isomorphic software systems. We find Haxe w/ Kha quick for prototyping and increasingly promising as the build targets evolve.  BTW- great live feed of your drawing skills recently on YouTube.

**Comment by lewislepton** [comment]
my main love for kha is that the syntax makes sense. much like c++ or other things like that. openfl & haxeflixel are great in there own right. but ive never been a flash person & dont like the flash type syntax ;)
plus the whole thing of building is just great.

cool about the isomorphic. is there anything online to look at or run?

also thanks about the art streams. doing another tomorrow. something a bit more... fun id say ;)
also looking to expand streaming to doing coding stuff. so prep for tutorials etc. would be the recordings themselves, but just a way people can see what is happening or even the thought process.
more can be found [**HERE**](https://www.patreon.com/posts/last-of-nape-11343041)

**Comment by EricEisaman** [comment]
@lewislepton  The only isomorphic HTML5 builds I have online are super simple demos for my students. [Here](https://ericeisaman.github.io/mod6.html) is an HTML5 demo of force based motion with Haxe and Stencyl.  [Here](https://ericeisaman.github.io/mod7.html) is the HTML5 demo shown above build with Kha. Once our school year ends I hope to build a couple serious apps.

Thanks to the link to the nape tutorials.

**Comment by lewislepton** [comment]
stencyl seems nice. when i found out it was haxe, then i didnt bother. but it looks a great platform to get to know things ;)
nice html5 demo. reminds me i need to revisit zui, since much has changed in it since i first done tutorials on it.

aye. i decided to end the nape tutorials. so recorded 5 a day or so ago [still need to edit & make available on patreon first ;)]. but think its enough nape for now. plenty for people to look at but even ask questions to themselves to do some exploring on there own ;)
